//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.05 at 11:43:16 AM CDT 
//


package org.jasig.maven.notice.lookup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jasig.maven.notice.lookup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jasig.maven.notice.lookup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArtifactLicense }
     * 
     */
    public ArtifactLicense createArtifactLicense() {
        return new ArtifactLicense();
    }

    /**
     * Create an instance of {@link MappedVersion }
     * 
     */
    public MappedVersion createMappedVersion() {
        return new MappedVersion();
    }

    /**
     * Create an instance of {@link LicenseLookup }
     * 
     */
    public LicenseLookup createLicenseLookup() {
        return new LicenseLookup();
    }

}
